### ISSUE TITLE
It would be cool to have a default CSS file

### ISSUE THREAD

**Issue by danqing** [datuhealth/floating-label#16]
Since it looks like the JS itself won't be enough. It'd be great to have a sample css to start with.

**Comment by mike-engel** [comment]
@danqing How would you ideally consume this stylesheet? Would you download it from this repo or would you consume it from the npm/bower package?

**Comment by danqing** [comment]
I guess download from the repo? Pretty much what will be enough is to get the styles from `index.html` out into its own thing.

**Comment by mike-engel** [comment]
Ok cool, I'll try to get to it tonight.

**Comment by mike-engel** [comment]
Closing this issue as this project is no longer being maintained.
